### ISSUE TITLE
[Feature][Blog] Increase the number of blog posts

### ISSUE THREAD

**Issue by rookiegao** [SophiaData/Bigdata_Note#53]
### Search before asking

- [X] I had searched in the [issues](https://github.com/SophiaData/Bigdata_Note/issues) and found no similar feature requirement.

### Description

Add more articles to the blog and adjust the blog layout appropriately

blog link
https://bigdata-note.readthedocs.io/zh_CN/latest/

### Use case

Blogs become basically available by adding new articles and adjusting the layout

### Related issues

none

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xingjieshitu** [comment]
good idea
